name: CloudFormation Lint & Validate
on:
  pull_request:
    branches: ["**"]
  push:
    branches: ["main"]
jobs:
  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: |
          python -p pip install --upgrade pip || true
          pip install cfn-lint==0.*
      - run: |
          cfn-lint -i W -t cloudformation/network-security-controls.yaml
